
on: 
 workflow_dispatch:

name: Test validation

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
     - uses: actions/checkout@v1
     - name: Run ARM-TTK with 'path'
       uses: venura9/arm-ttk@master
       id: path-test
       with: 
        path: ./Modules

     - name: Results for Run ARM-TTK with 'path'
       run: |
          content=${{ steps.path-test.outputs.results }}
          echo "Results $content"
    
     - name: Upload Build Artifact
       uses: actions/upload-artifact@v2.2.4
       with:
          name: BuildArtifacts
          path: ./
