
on: 
 workflow_dispatch:

name: Test validation

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
     - uses: actions/checkout@v1
     - uses: Zingabopp/JsonValidate-Action@v1
       with:
        json-schema:  http://json-schema.org
        json-file:  ./Modules
    
     - name: Upload Build Artifact
       uses: actions/upload-artifact@v2.2.4
       with:
          name: BuildArtifacts
          path: ./
