
on: 
 workflow_dispatch:

name: Test validation

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
     - uses: actions/checkout@v1

  #   - name: validate
  #     run: find ./Modules | grep .json | xargs -L1 python -mjson.tool > /dev/null
  #     shell: bash
  
     - name: Validate BigQuery schema
        uses: snapcart/json-schema-validator@v1
        with:
         json_schema: ./Modules
         send_comment : true
         clear-comment : true
    
     - name: Upload Build Artifact
       uses: actions/upload-artifact@v2.2.4
       with:
          name: BuildArtifacts
          path: ./
