name: Docs/Wiki Sync

on:
  workflow_dispatch:
          
env:
  wiki_source_repo: "khossain-insight/mynewrepo"
  wiki_source_repo_dir: "khossain-insight/*"
  wiki_target_repo: "khossain-insight/mynewrepo.wiki"
  github_user_name: "khossain-insight"
  github_email: "mdkowser.hossain@insight.com"
  github_commit_message: "Wiki Sync from docs/wiki"

jobs:
  sync-wiki:
    name: Sync docs/wiki to Wiki
    if: github.repository == 'khossain-insight/mynewrepo'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.wiki_source_repo }}
          path: ${{ env.wiki_source_repo }}

      - name: Checkout Wiki Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.wiki_target_repo }}
          path: ${{ env.wiki_target_repo }}

      - name: Configure Local Git
        run: |
          git config --global user.name $github_user_name
          git config --global user.email $github_email
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Sync docs/wiki Into Wiki Repo
        run: |
          rsync -avzr --delete --exclude='.git/' "$wiki_source_repo_dir/" "$wiki_target_repo"
        working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Stage & Push Files Into Wiki Repo
        run: |
          git add .
          git commit -m "$github_commit_message [$GITHUB_ACTOR/${GITHUB_SHA::8}]"
          git push --set-upstream https://$GITHUB_TOKEN@github.com/$wiki_target_repo.git master
        working-directory: ${{ env.wiki_target_repo }}
